In [25]:
#**Задание 1**
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

import numpy as np
def array_generator(start):
    if start == 0:
        return np.array( [ 0 ] )
    elif start < 0:
        return np.arange(start+1,1,1)
    else:
        return np.arange(start-1,-1,-1)
    
array_generator(-5000)

array([-4999, -4998, -4997, ...,    -2,    -1,     0])

In [38]:
#**Задание 2**
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

x = np.diag(np.arange(9,-1,-1), k=0)
x


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
x.sum()

45

In [26]:
#**Задание 3**
#Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


import pandas as pd
movies_dt = pd.read_csv('movies.csv')
ratings_dt = pd.read_csv('ratings.csv')

# создаем общую таблицу Х
x = ratings_dt.merge(movies_dt, how='inner')

#фильтруем таблицу Х по оценке 5.0
x = x[x['rating'] == 5.0]

#считаем количество значений с группировкой по названию (вместо кода фильма)
x['title'].value_counts()



Shawshank Redemption, The (1994)                                                     153
Pulp Fiction (1994)                                                                  123
Forrest Gump (1994)                                                                  116
Matrix, The (1999)                                                                   109
Star Wars: Episode IV - A New Hope (1977)                                            104
Silence of the Lambs, The (1991)                                                      92
Schindler's List (1993)                                                               92
Godfather, The (1972)                                                                 88
Fight Club (1999)                                                                     81
Star Wars: Episode V - The Empire Strikes Back (1980)                                 80
Braveheart (1995)                                                                     80
Usual Suspects, The (

In [61]:
#**Задание 4**
#По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. 
#Не учитывайте в расчетах отрицательные значения quantity.

data = pd.read_csv('power.csv')

#сначала фильтруем по странам и категориям
filtered_countries = data[((data['country'] == 'Latvia') | (data['country']=='Lithuania') | (data['country']=='Estonia'))&((data['category'] == 4) | (data['category'] == 12)| (data['category'] == 21))]

#затем оставляем только нужные годы и положительные значения
filtered_countries = filtered_countries[(filtered_countries['year'] > 2004) & (filtered_countries['year'] < 2011) & filtered_countries['quantity'] > 0]

#старый знакомый груп-бай по количеству энергии, единичка позволяет обойтись без разбивки
filtered_countries.groupby('country')['quantity'].sum()[1]

54844.0

In [62]:
#**Задание 5**
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 1, 0], [2, 3, 5], [1, 0, 4] ] )

# значения в правой части уравнения
b = np.array( [4, 12, -3] )

# и решаем
from numpy import linalg
linalg.solve(a, b)

array([-0.33333333,  5.33333333, -0.66666667])

In [63]:
# проверяем для надёжности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True